services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  docs:
    build: ./backend
    ports:
      - "5004:5004"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python app_swagger.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5004/docs-menu"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      - docs
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - BACKEND_URL=http://backend:5002
    command: python app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
